version: "3.9"

services:
  jupyterhub:
    build:
      context: .
      args:
        JUPYTER_ADMIN_USER: "${JUPYTER_ADMIN_USER}"
        JUPYTER_ADMIN_PASSWORD: "${JUPYTER_ADMIN_PASSWORD}"
    container_name: jupyterhub_server
    env_file:
      - .env
    ports:
      - "8000:8000"
    # volumes:
    #   - ./qmt:/home/${JUPYTER_ADMIN_USER}/qmt  # Mount qmt without copying
    #   - ./notebooks:/home/${JUPYTER_ADMIN_USER}/notebooks  # Persist notebooks
    #   - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py  # Config file
    restart: unless-stopped
